version: "3.7"

services:
  #nginx
  web:
    build: ./docker/nginx
    container_name: web
    ports:
      # - "8080:80"
      - "8080:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/share/nginx/html
    depends_on: 
      - app
  #php
  app:
    build: ./docker/php
    container_name: app
    volumes:
      - ./app:/var/www/html
    env_file:
      - ./docker/php/setting.env
    depends_on: 
      - db
  # mysql
  db:
    build: ./docker/mysql
    container_name: db
    env_file:
      - ./docker/mysql/setting.env
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

volumes:
  mysql-data:
    name: mysql-volume
