spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampledb
    username: sample_user
    password: sample_user
#flyway:
#  url: jdbc:mysql://localhost:3306/sampledb
#  user: sample_user
#  password: sample_user
