version: "3.7"

services:
  db:
    build: ./docker/mysql
    container_name: db
    env_file:
      - ./docker/mysql/setting.env
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

volumes:
  mysql-data:
    name: mysql-volume
